Dependency Updates, and fix scripts
hpi-schul-cloud/node-notification-service pull request #250
Opened 2020-09-10 13:23 UTC by tofixx

2020-09-10 13:24 UTC, CeEv submitted a review, later dismissed

2020-09-10 13:26 UTC, CeEv approved these changes

2020-09-14 08:01 UTC, CeEv requested changes

2020-09-14 08:13 UTC, tofixx commented on src/interfaces/Mail.ts
> +	attachments?: Array<{ content: Buffer | string; filename: string }>;
As this is an interface, semicolon is valid here (as for the properties around). https://medium.com/swlh/typescript-best-practices-delimiters-and-ordering-7feb42e0ca1d#:~:text=In%20TypeScript%2C%20interfaces%20and%20type,a%20comma%20or%20a%20semicolon.&text=They're%20both%20valid%2C%20but%20TypeScript%20prefers%20semicolon.

2020-09-14 08:16 UTC, tofixx commented on src/routes/message.ts
> +		if (req.body.redirect && message && message.payload && req.body.redirect in message.payload) {
We have a line-length defined, which is `printWidth: 120`. This line has a width of 103 only.

2020-09-14 09:18 UTC, CeEv commented on src/interfaces/Mail.ts
> +	attachments?: Array<{ content: Buffer | string; filename: string }>;
ok

2020-09-14 09:29 UTC, tofixx commented on src/models/message.ts
> +	{
sure, but specific things in prettier may be overridden by eslint

2020-09-14 09:34 UTC, CeEv approved these changes

2020-09-14 10:01 UTC, merged